export default {
  container: {
    marginLeft: "auto",
    marginRight: "auto",
    marginVertical: 0,
    paddingVertical: 0,
    paddingHorizontal: 15,
    maxWidth: 480,
  },
  footer: { background: "#90937e30" },
  footerBlock: {
    display: "flex",
    paddingVertical: 40,
    paddingHorizontal: 0,
  },
  footerContent: { display: "flex" },
  footerLogoLink: { display: "flex", alignItems: "center", maxHeight: 100 },
  footerLogoImg: { maxWidth: 40, maxHeight: 40, marginRight: 5 },
  footerLogoTitle: { color: "#4a3a2b", fontSize: 30, marginLeft: 5 },
  footerLogoTitleSpan: { color: "#375215", fontWeight: "bold" },
  footerMenu: { display: "flex", flexDirection: "column" },
  footerItem: { marginBottom: 10 },
  footerItemLink: {
    position: "relative",
    color: "#375215",
    fontSize: 19,
    fontWeight: 500,
    cursor: "pointer",
    paddingBottom: 2,
  },
  footerAuthor: {
    paddingVertical: 20,
    paddingHorizontal: 0,
    borderTopColor: "rgba(0, 0, 0, 0.5)",
    borderTopWidth: 1,
    display: "flex",
    justifyContent: "space-between",
  },
  footerAuthorOwnSpan: { color: "#375215", fontWeight: 600 },
};
