export default {
  heroContent: {
    backgroundRepeat: "no-repeat",
    backgroundPosition: "top",
    height: 300,
  },
  heroBlock: {
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    height: 300,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  heroTitle: { fontSize: 35, color: "white", marginBottom: 15 },
  heroTitleSpan: { color: "#8eff00" },
  heroText: {
    fontSize: 15,
    color: "#fefefedb",
    textAlign: "justify",
    lineHeight: 21,
    maxWidth: 560,
    marginLeft: "auto",
    marginRight: "auto",
    marginVertical: 0,
    marginBottom: 10,
    paddingVertical: 0,
    paddingHorizontal: 20,
  },
  heroTextSpan1: { color: "white", fontSize: 15 },
  heroTextSpan2: { color: "#8eff00", fontSize: 15, marginLeft: 5 },
  heroButton: {
    position: "relative",
    borderWidth: 1,
    borderColor: "#8eff00",
    paddingVertical: 5,
    paddingHorizontal: 15,
    display: "flex",
    alignItems: "center",
    transition: "all 250ms linear",
    cursor: "pointer",
    borderRadius: 5,
  },
  heroButtonText: {
    color: "white",
    fontSize: 27,
    fontWeight: 400,
    zIndex: 1,
  },
};
